More verbose error messages

diff --git a/cmake/linux/package_linux.sh.in b/cmake/linux/package_linux.sh.in
--- a/cmake/linux/package_linux.sh.in
+++ b/cmake/linux/package_linux.sh.in
@@ -6,11 +6,10 @@
 # Notes:    Will attempt to fetch linuxdeployqt automatically (x86_64 only)
 #           See Also: https://github.com/probonopd/linuxdeployqt/blob/master/BUILDING.md
 
-set -e
+trap "error 'Failed to generate AppImage'; exit 1" ERR
 
 LINUXDEPLOYQT="@CMAKE_BINARY_DIR@/linuxdeployqt"
 VERBOSITY=2 # 3=debug
-LOGFILE="@CMAKE_BINARY_DIR@/appimage.log"
 APPDIR="@CMAKE_BINARY_DIR@/@PROJECT_NAME_UCASE@.AppDir/"
 DESKTOPFILE="${APPDIR}usr/share/applications/lmms.desktop"
 STRIP=""
@@ -40,6 +39,13 @@ function skipped {
 	echo -e "   ${PLAIN}[${YELLOW}skipped${PLAIN}] ${1}"
 }
 
+# Run a command silently, but print output if it fails
+function try_quiet {
+    output="$("$@" 2>&1)" && return
+    printf '%s\n' "$output"
+    return 1
+}
+
 # Blindly assume system arch is appimage arch
 ARCH=$(uname -m)
 export ARCH
@@ -49,8 +55,6 @@ INSTALL=$(echo "@CMAKE_INSTALL_PREFIX@" | sed 's/\/*$//g')
 if [ "$INSTALL" == "/usr/local" ] || [ "$INSTALL" == "/usr" ] ; then
 	error "Incompatible CMAKE_INSTALL_PREFIX for creating AppImage: @CMAKE_INSTALL_PREFIX@"
 fi
-
-echo -e "\nWriting verbose output to \"${LOGFILE}\""
 
 # Ensure linuxdeployqt uses the same qmake version as cmake
 PATH="$(pwd -P)/squashfs-root/usr/bin:$(dirname "@QT_QMAKE_EXECUTABLE@")":$PATH
@@ -65,11 +69,17 @@ else
 	filename="linuxdeployqt-continuous-$ARCH.AppImage"
 	url="https://github.com/probonopd/linuxdeployqt/releases/download/continuous/$filename"
 	down_file="$(pwd)/$filename"
-	if [ ! -f "$LINUXDEPLOYQT" ]; then
+	if [ ! -L "$LINUXDEPLOYQT" ]; then
 		ln -s "$down_file" "$LINUXDEPLOYQT"
 	fi
-	echo "   [.......] Downloading ($(uname -p)): ${url}"
-	wget -N -q "$url" || (rm "$filename" && false)
+	echo "   [.......] Downloading: ${url}"
+	wget -N -q "$url" || errorcode=$?
+	if [ "$errorcode" == 8 ]; then
+		# Server issued an error response
+		error "No package available for architecture: $ARCH"
+	elif [ "$errorcode" ]; then
+		error "Download failed"
+	fi
 	chmod +x "$LINUXDEPLOYQT"
 	success "Downloaded $LINUXDEPLOYQT"
 	# Extract AppImage and replace LINUXDEPLOYQT variable with extracted binary
@@ -151,10 +161,9 @@ executables="${executables} -executable=${APPDIR}usr/lib/lmms/ladspa/pitch_scale
 
 # Bundle both qt and non-qt dependencies into appimage format
 echo -e "\nBundling and relinking system dependencies..."
-echo -e ">>>>> linuxdeployqt" > "$LOGFILE"
 
 # shellcheck disable=SC2086
-"$LINUXDEPLOYQT" "$DESKTOPFILE" $executables -bundle-non-qt-libs -verbose=$VERBOSITY $STRIP >> "$LOGFILE" 2>&1
+try_quiet "$LINUXDEPLOYQT" "$DESKTOPFILE" $executables -bundle-non-qt-libs -verbose=$VERBOSITY $STRIP
 success "Bundled and relinked dependencies"
 
 # Link to original location so lmms can find them
@@ -187,8 +196,7 @@ ln -sr "${APPDIR}/usr/bin/lmms" "${APPDIR}/AppRun"
 
 # Create AppImage
 echo -e "\nFinishing the AppImage..."
-echo -e "\n\n>>>>> appimagetool" >> "$LOGFILE"
-"$APPIMAGETOOL" "${APPDIR}" "@APPIMAGE_FILE@" >> "$LOGFILE" 2>&1
+try_quiet "$APPIMAGETOOL" "${APPDIR}" "@APPIMAGE_FILE@"
 success "Created @APPIMAGE_FILE@"
 
 echo -e "\nFinished"
