Respect env variables, revert deletion of log file

diff --git a/cmake/linux/package_linux.sh.in b/cmake/linux/package_linux.sh.in
--- a/cmake/linux/package_linux.sh.in
+++ b/cmake/linux/package_linux.sh.in
@@ -6,10 +6,8 @@
 # Notes:    Will attempt to fetch linuxdeployqt automatically (x86_64 only)
 #           See Also: https://github.com/probonopd/linuxdeployqt/blob/master/BUILDING.md
 
-trap "error 'Failed to generate AppImage'; exit 1" ERR
-
-LINUXDEPLOYQT="@CMAKE_BINARY_DIR@/linuxdeployqt"
 VERBOSITY=2 # 3=debug
+LOGFILE="@CMAKE_BINARY_DIR@/appimage.log"
 APPDIR="@CMAKE_BINARY_DIR@/@PROJECT_NAME_UCASE@.AppDir/"
 DESKTOPFILE="${APPDIR}usr/share/applications/lmms.desktop"
 STRIP=""
@@ -39,11 +37,17 @@ function skipped {
 	echo -e "   ${PLAIN}[${YELLOW}skipped${PLAIN}] ${1}"
 }
 
+# Exit with error message if any command fails
+trap "error 'Failed to generate AppImage'; exit 1" ERR
+
 # Run a command silently, but print output if it fails
-function try_quiet {
-    output="$("$@" 2>&1)" && return
-    echo "$output"
-    return 1
+function run_and_log {
+	echo -e "\n\n>>>>> $1" >> "$LOGFILE"
+	output="$("$@" 2>&1)"
+	status=$?
+	echo "$output" >> "$LOGFILE"
+	[[ $status != 0 ]] && echo "$output"
+	return $status
 }
 
 # Blindly assume system arch is appimage arch
@@ -56,39 +60,39 @@ if [ "$INSTALL" == "/usr/local" ] || [ "$INSTALL" == "/usr" ] ; then
 	error "Incompatible CMAKE_INSTALL_PREFIX for creating AppImage: @CMAKE_INSTALL_PREFIX@"
 fi
 
+# Include content of linuxdeployqt's extracted AppImage in PATH
 # Ensure linuxdeployqt uses the same qmake version as cmake
 PATH="$(pwd -P)/squashfs-root/usr/bin:$(dirname "@QT_QMAKE_EXECUTABLE@")":$PATH
 export PATH
 
+# Use linuxdeployqt from env or in PATH
+[[ $LINUXDEPLOYQT ]] || LINUXDEPLOYQT="$(which linuxdeployqt 2>/dev/null)" || true
+[[ $APPIMAGETOOL ]] || APPIMAGETOOL="$(which appimagetool 2>/dev/null)" || true
+
 # Fetch portable linuxdeployqt if not in PATH
-APPIMAGETOOL="squashfs-root/usr/bin/appimagetool"
-echo -e "\nDownloading linuxdeployqt to ${LINUXDEPLOYQT}..."
-if env -i which linuxdeployqt > /dev/null 2>&1; then
-	skipped "System already provides this utility"
-else
+if [[ -z $LINUXDEPLOYQT || -z $APPIMAGETOOL ]]; then
 	filename="linuxdeployqt-continuous-$ARCH.AppImage"
 	url="https://github.com/probonopd/linuxdeployqt/releases/download/continuous/$filename"
-	down_file="$(pwd)/$filename"
-	if [ ! -L "$LINUXDEPLOYQT" ]; then
-		ln -s "$down_file" "$LINUXDEPLOYQT"
-	fi
 	echo "   [.......] Downloading: ${url}"
-	wget -N -q "$url" || errorcode=$?
-	if [ "$errorcode" == 8 ]; then
-		# Server issued an error response
-		error "No package available for architecture: $ARCH"
-	elif [ "$errorcode" ]; then
-		error "Download failed"
-	fi
-	chmod +x "$LINUXDEPLOYQT"
-	success "Downloaded $LINUXDEPLOYQT"
+	wget -N -q "$url" && err=0 || err=$?
+	case "$err" in
+		0) success "Downloaded $PWD/$filename" ;;
+		# 8 == server issued 4xx error
+		8) error "Download failed (perhaps no package available for $ARCH)" ;;
+		*) error "Download failed" ;;
+	esac
+
 	# Extract AppImage and replace LINUXDEPLOYQT variable with extracted binary
 	# to support systems without fuse
 	# Also, we need to set LD_LIBRARY_PATH, but linuxdepoyqt's AppRun unsets it
 	# See https://github.com/probonopd/linuxdeployqt/pull/370/
-	"$LINUXDEPLOYQT" --appimage-extract > /dev/null 2>&1
-	LINUXDEPLOYQT="squashfs-root/usr/bin/linuxdeployqt"
-	success "Extracted $APPIMAGETOOL"
+	chmod +x "$filename"
+	"$filename" --appimage-extract > /dev/null 2>&1
+	success "Extracted $filename"
+
+	# We set PATH earlier to include the extracted ./squashfs-root
+	[[ $LINUXDEPLOYQT ]] || LINUXDEPLOYQT="$(which linuxdeployqt)"
+	[[ $APPIMAGETOOL ]] || APPIMAGETOOL="$(which appimagetool)"
 fi
 
 # Make skeleton AppDir
@@ -159,11 +163,14 @@ executables="${executables} -executable=${APPDIR}usr/lib/lmms/ladspa/imbeq_1197.
 executables="${executables} -executable=${APPDIR}usr/lib/lmms/ladspa/pitch_scale_1193.so"
 executables="${executables} -executable=${APPDIR}usr/lib/lmms/ladspa/pitch_scale_1194.so"
 
+echo -e "\nWriting verbose output to \"${LOGFILE}\""
+echo -n > "$LOGFILE"
+
 # Bundle both qt and non-qt dependencies into appimage format
 echo -e "\nBundling and relinking system dependencies..."
 
 # shellcheck disable=SC2086
-try_quiet "$LINUXDEPLOYQT" "$DESKTOPFILE" $executables -bundle-non-qt-libs -verbose=$VERBOSITY $STRIP
+run_and_log "$LINUXDEPLOYQT" "$DESKTOPFILE" $executables -bundle-non-qt-libs -verbose=$VERBOSITY $STRIP
 success "Bundled and relinked dependencies"
 
 # Link to original location so lmms can find them
@@ -196,7 +203,7 @@ ln -sr "${APPDIR}/usr/bin/lmms" "${APPDIR}/AppRun"
 
 # Create AppImage
 echo -e "\nFinishing the AppImage..."
-try_quiet "$APPIMAGETOOL" "${APPDIR}" "@APPIMAGE_FILE@"
+run_and_log "$APPIMAGETOOL" "${APPDIR}" "@APPIMAGE_FILE@"
 success "Created @APPIMAGE_FILE@"
 
 echo -e "\nFinished"
